# Generated by Django 3.2 on 2021-10-13 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Nom'),
            preserve_default=False,
        ),
    ]
