# Generated by Django 3.2 on 2021-10-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_home_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carossel',
            name='frst_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='carossel',
            name='scd_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='carossel',
            name='trd_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='home_page',
            name='about_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
