# Generated by Django 3.2 on 2021-10-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211013_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carossel',
            name='frst_image',
            field=models.ImageField(upload_to='main/images/carossels'),
        ),
        migrations.AlterField(
            model_name='carossel',
            name='scd_image',
            field=models.ImageField(upload_to='main/images/carossels'),
        ),
        migrations.AlterField(
            model_name='carossel',
            name='trd_image',
            field=models.ImageField(upload_to='main/images/carossels'),
        ),
        migrations.AlterField(
            model_name='home_page',
            name='about_image',
            field=models.ImageField(upload_to='main/images/home_page'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='main/images/services'),
        ),
    ]
